apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hetznerauctionbot-pro
  namespace: argocd
spec:
  destination:
    namespace: hetznerauctionbot-pro
    server: 'https://kubernetes.default.svc'
  source:
    path: cicd/pro
    repoURL: 'https://github.com/soukron/hetznerauctionbot'
    targetRevision: master
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

