apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    labels:
      app: notifier
    name: notifier
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    labels:
      app: bot
    name: bot
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: notifier
    name: notifier
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: notifier:latest
    source:
      git:
        uri: https://github.com/hetznerauctionbot/notifier.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:8
          namespace: openshift
      type: Source
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: bot
    name: bot
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: bot:latest
    source:
      git:
        uri: https://github.com/hetznerauctionbot/bot.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:8
          namespace: openshift
      type: Source
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: notifier-bot
    name: notifier-bot
  spec:
    replicas: 1
    selector:
      name: notifier-bot
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: notifier-bot
        name: notifier-bot
      spec:
        containers:
        - env:
          - name: TELEGRAM_KEY
            valueFrom:
              secretKeyRef:
                key: key
                name: telegram-config-secret
          - name: TELEGRAM_CHATID
            valueFrom:
              secretKeyRef:
                key: chatid
                name: telegram-config-secret
          image: image-registry.openshift-image-registry.svc:5000/hetznerbiddingbot-pro/notifier:latest
          name: notifier
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
          - name: shared-data
            mountPath: /opt/app-root/src/data
        - env:
          - name: TELEGRAM_KEY
            valueFrom:
              secretKeyRef:
                key: key
                name: telegram-config-secret
          image: image-registry.openshift-image-registry.svc:5000/hetznerbiddingbot-pro/bot:latest
          name: bot
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
          - name: shared-data
            mountPath: /opt/app-root/src/data
        volumes:
        - name: shared-data
          emptyDir: {}
    triggers:
    - type: ConfigChange
